//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_QuanLyDiemHocSinh_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAI_KHOAN
    {
        public int MaTK { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string VaiTro { get; set; }
        public Nullable<int> MaHS { get; set; }
        public Nullable<int> MaGV { get; set; }
    
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        public virtual HOC_SINH HOC_SINH { get; set; }
    }
}
