//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_QuanLyDiemHocSinh_CallAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM
    {
        public int MaHS { get; set; }
        public int MaMon { get; set; }
        public byte HocKy { get; set; }
        public string NamHoc { get; set; }
        public Nullable<double> DiemKT { get; set; }
        public Nullable<double> DiemGK { get; set; }
        public Nullable<double> DiemThi { get; set; }
    
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual MON_HOC MON_HOC { get; set; }
    }
}
