//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_QuanLyDiemHocSinh_CallAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANG_DAY
    {
        public int MaLop { get; set; }
        public int MaGV { get; set; }
        public int MaMon { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> PhongHoc { get; set; }
    
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MON_HOC MON_HOC { get; set; }
    }
}
