//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_QuanLyDiemHocSinh_CallAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MON_HOC()
        {
            this.DIEMs = new HashSet<DIEM>();
            this.GIANG_DAY = new HashSet<GIANG_DAY>();
        }
    
        public int MaMon { get; set; }
        public string TenMon { get; set; }
        public Nullable<int> SoTiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM> DIEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIANG_DAY> GIANG_DAY { get; set; }
    }
}
